Textual html editor integration + bugfixes
France-ioi/visual-html-editor pull request #4
Opened 2021-05-26 14:34 UTC by MushkyQT

This PR mainly targets the textual editor functionality by integrating the ACE editor. Some refactoring has been done in various areas of the app as well, notably splitting the editorconfig.ts file into 3 files (appconfig, toolboxconfig, editorconfig). Some bugfixes for the visual editor are included as well.

Textual editor info:
Implemented ACE using react-ace library and ace-builds. Configured ACE & ACE drag & drop support. Using isTouchDevice() fn, load forked 'mobile-drag-drop' touch api polyfill for HTML5 dnd api. Use js-beautify.html to format code for insertion into ACE as one big string. Can switch from visual to textual editors on the fly and persist code.
Note: I forked mobile-drag-drop shim to change one line of code which stripped all classes from elements during drag. Removing this line means our dragged elements will render correctly during a drag.

Main bugs fixed & changes:
- [x]  Fix bug when typing punctuation in Textual mode, disappears in Visual
- [x]  H1 elements should be on same line & p tags should be block level
- [x]  Homogenize fonts and styles for all editors and toolbox
- [x]  Update regex to handle tags with attributes & also work on iOS (removed lookbehind)
- [x]  Polyfill for HTML5 dnd API to work with touch (mobile devices) and mobile-related style changes
- [x] Visual bug when dragging from categories besides 1 (due to non unique category block ids)
- [x] Locked & unlocked tags same color
- [x] Fix tag position relative to cursor on desktop and mobile devices
- [x] Self-closing tags should be square instead of angled

2021-05-27 12:17 UTC, SebastienTainon requested changes

2021-05-27 12:17 UTC, SebastienTainon commented on src/appconfig.ts
> +export const toolboxBlocks = {
You should type the variable when it's declared (ie here) instead of when it's used (in `src/toolboxconfig.ts`)

2021-05-27 12:17 UTC, SebastienTainon commented on src/editorconfig.ts
> +  if (tag.type !== 'text') {
TagType.Text

2021-05-27 12:17 UTC, SebastienTainon commented on src/editorconfig.ts
> +    returnTag = tag.type === 'closing' ? `</${tag.value}>` : `<${tag.value}>`
TagType.Closing, please use the enums you have defined :wink:

2021-05-27 12:17 UTC, SebastienTainon commented on src/features/blocks/Block.tsx
> +    if (editorMode === 'visual') {
EditorType.Visual

2021-05-27 12:17 UTC, SebastienTainon commented on src/features/editors/TextualHTMLEditor.tsx
> +interface ITextualHTMLEditor {
Suggestion: name this `TextualHTMLEditorProps` (and idem in the other components). It's more explicit than having this "I" before the name of the component because this not an interface for the component itself but for its props. The convention `{ComponentName}Props` looks better.

2021-06-08 14:07 UTC, MushkyQT commented on src/features/editors/TextualHTMLEditor.tsx
> +interface ITextualHTMLEditor {
Understood, changed all relevant names!

2021-06-08 14:23 UTC, SebastienTainon approved these changes

2021-06-08 16:58 UTC, merged